go:
    image: cityos/go-host
    restart: always
    volumes:
        - ./claire/src/backend:/go/src/app
        #- ~/go/src/github.com/aneshas/claire-go-backend:/go/src/app
    links:
        - mysql
    entrypoint: /idle.sh
nginx:
    image: nginx
    restart: always
    volumes:
        - ./claire/conf/nginx:/etc/nginx/conf.d
        - ./claire/src/frontend:/usr/share/nginx/html
    ports:
        - "80:80"
    links:
        - go
mysql:
    image: mysql
    restart: always
    volumes:
        - ./claire/src/db:/data
        - ./claire/conf/mysql:/etc/mysql/conf.d
    environment:
        - MYSQL_DATABASE=claire
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
