go:
    image: cityos/go-host
    restart: always
    volumes:
        # TODO change to ./claire/src/backend:/go/src/app
        - ~/go/src/github.com/aneshas/claire-go-backend:/go/src/app
    links:
        - mysql
    #entrypoint: /run.sh
    entrypoint: /idle.sh
nginx:
    image: nginx
    restart: always
    volumes:
        - ./claire/conf/nginx:/etc/nginx/conf.d
        - ./claire/src/frontend:/usr/share/nginx/html
    ports:
        - 80:80
        - 443:443
    links:
        - go
mysql:
    image: mysql
    restart: always
    volumes:
        - ./claire/volumes/mysql:/var/lib/mysql
        - ./claire/conf/mysql:/etc/mysql/conf.d
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
